version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.dev.env

  backend:
    build:
      context: ../api_spot
    restart: always
    volumes:
      - static_value:/app/static
      - media_value:/app/media
      - app_value:/app
    depends_on:
      - db
    env_file:
      - ./.dev.env

  redis:
    image: redis:latest
    restart: always

  celery:
    build:
      context: ../api_spot
    command: celery -A api_spot worker --loglevel=info
    restart: always
    volumes:
      - app_value:/app
    depends_on:
      - backend
      - redis
    env_file:
      - ./.dev.env

  celery_beat:
      build:
        context: ../api_spot
      command: celery -A api_spot beat --loglevel=info
      restart: always
      volumes:
      - app_value:/app
      depends_on:
        - backend
        - redis
        - celery
      env_file:
        - ./.dev.env

  flower:
    image: mher/flower
    restart: always
    expose:
      - 5555
    env_file:
      - ./.dev.env
    depends_on:
      - backend
      - redis
      - celery
      - celery_beat
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/devconf.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    links:
      - backend
    depends_on:
      - backend
      - flower
      - frontend

volumes:
  static_value:
  media_value:
  postgres_data:
  frontend: